# Generated by Django 6.0.4 on 2026-04-17 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pledges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('stripe', 'Carte bancaire'), ('bank_transfer', 'Virement bancaire'), ('cmi', 'CMI (Maroc)')], max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiée'), ('completed', 'Complétée'), ('failed', 'Échouée'), ('refunded', 'Remboursée')], default='initiated', max_length=20)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pledge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='pledges.pledge')),
            ],
        ),
    ]
