# Generated by Django 6.0.4 on 2026-04-17 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('failed', 'Échouée'), ('refunded', 'Remboursée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=200)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.project')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='rewards.reward')),
            ],
        ),
    ]
