# Generated by Django 6.0.4 on 2026-04-17 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#3498db', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funding_type', models.CharField(choices=[('all_or_nothing', 'Tout ou rien'), ('flexible', 'Flexible')], default='all_or_nothing', max_length=20)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('active', 'Actif'), ('funded', 'Financé'), ('failed', 'Non financé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('video_url', models.URLField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('backers_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
