# Generated by Django 6.0.4 on 2026-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Telephone'), ('both', 'Email et telephone')], default='email', max_length=10),
        ),
    ]
