# Generated by Django 6.0.4 on 2026-05-01 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('account', 'Compte'), ('project', 'Projet'), ('payment', 'Paiement'), ('pledge', 'Contribution'), ('technical', 'Probleme technique'), ('other', 'Autre')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('urgent', 'Urgente')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Resolu'), ('closed', 'Ferme')], default='open', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_tickets.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
