# Generated by Django 6.0.4 on 2026-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('donation_created', 'Donation creee'), ('payment_confirmed', 'Paiement confirme'), ('reward_selected', 'Recompense selectionnee'), ('pledge_received', 'Nouvelle contribution'), ('project_funded', 'Projet finance'), ('project_updated', 'Mise a jour projet'), ('project_approved', 'Projet approuve'), ('project_rejected', 'Projet refuse'), ('comment_reply', 'Reponse commentaire')], max_length=30),
        ),
    ]
